accounts/urls.py
from django.urls import path, include

from . import views

app_name = "accounts"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("profile/", views.profile, name='profile'),
    path("signup/", views.SignUpView.as_view(), name='signup'),
    path("signin/", views.signin, name='signin'),
]

api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('auth/', include('rest_framework.urls')),
    path('users/', views.UserList.as_view(), name='users'),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('hello', views.ApiEndpoint.as_view()),
    path('secret', views.secret_page, name='secret'),
]

djangoUnchained/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("main.urls")),
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

snippets/urls.py
from django.urls import path

from . import views

app_name = "snippets"
urlpatterns = [
    # path('', views.snippet_list),
    # path('<int:pk>/', views.snippet_detail),
    path('', views.SnippetList.as_view(), name='list'),
    path('<int:pk>/', views.SnippetDetail.as_view()),
]

unchained/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("accounts.urls")),
    path('', include("main.urls")),
    path("polls/", include("polls.urls")),
    path("snippets/", include("snippets.urls")),
    path("api/", include("api.urls")),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html', {})

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Unchained</title>
    <style>
        body {
            margin: 5rem;
        }
    </style>
</head>
<body>

{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
    <h2>Permission</h2>
    <p><a href="{% url 'accounts:password_change' %}">Password Change</a></p>
    <a href="{% url 'accounts:profile' %}">Profile</a>
    <p></p>
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log Out</button>
    </form>
    <br>
    <h3>Admin</h3>
    <div>
        <p><a href="/admin">Admin</a></p>
    </div>
    <h3>Snippets</h3>
    <div>
        <p><a href="{% url 'snippets:list' %}">List</a></p>
    </div>
    <h3>API</h3>
    <div>
        <p><a href="{% url 'api:users' %}">Users</a></p>
    </div>
    <h3>Oauth Tool</h3>
    <div>
        <p><a href="{% url 'oauth2_provider:list' %}">Applications</a></p>
        <p><a href="{% url 'oauth2_provider:register' %}">Create Application</a></p>
        <p><a href="{% url 'oauth2_provider:authorize' %}">Authorize</a></p>
    </div>
{% else %}
    <p><a href="{% url 'accounts:password_reset' %}">Password Reset</a></p>
    <a href="{% url 'accounts:login' %}">Login</a>
    <p>Welcome, new user. Please log in.</p>
{% endif %}

</body>
</html>